### ISSUE TITLE
docs: Clarify form-data concepts or add examples for multiple languages

### ISSUE THREAD

**Issue by simenandre** [gotenberg/gotenberg.dev#4]
Hello,

Thank you for this fantastic project!

We've been rolling this out in our application and are very happy with the results. When we started, we went through the documentation (which is awesome btw!). We read the concept around header and footer, and we misunderstood this thing:

```shell
--form 'files=@"/path/to/header.html"' \
--form 'files=@"/path/to/footer.html"' \
```

It wasn't clear to us because none of us has been using `curl` to upload files. So I thought, maybe we can improve on this?

I thought maybe we could create examples for multiple languages? Or, example this more? Might just work by adding a simple alert?

I would love to contribute!

**Comment by cobraz** [comment]
Yeah, and I think it probably makes sense to keep it that way. I can try and make it clearer in a PR 👍
